# Generated by Django 5.1.5 on 2025-03-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tenant_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
