# Generated by Django 5.1.5 on 2025-03-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='1982-08-30'),
            preserve_default=False,
        ),
    ]
