# Generated by Django 5.1.4 on 2025-01-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome_funcionario', models.CharField(max_length=40, unique=True, verbose_name='Funcionário')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('carteira_trabalho', models.CharField(blank=True, max_length=12, null=True, verbose_name='Carteira Trabalho')),
                ('endereco', models.CharField(blank=True, max_length=40, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade')),
                ('telefone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone')),
                ('banco', models.CharField(blank=True, choices=[('Banco do Brasil', 'Banco do Brasil'), ('Banco Original', 'Banco Original'), ('Bradesco', 'Bradesco'), ('Caixa Econômica', 'Caixa Econômica'), ('C6 Bank', 'C6 Bank'), ('Itau', 'Itau'), ('Inter', 'Inter'), ('Neon', 'Neon'), ('Next', 'Next'), ('Nubank', 'Nubank'), ('Santander', 'Santander')], max_length=15, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=7, null=True, verbose_name='Agencia')),
                ('conta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Conta')),
                ('dt_atualizado', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateField(verbose_name='Data Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Pago')),
                ('tipo_pagamento', models.CharField(choices=[('Salário', 'Salário'), ('Adiantamento', 'Adiantamento'), ('Vale', 'Vale'), ('Vale Transporte', 'Vale Transporte'), ('Extra', 'Extra'), ('Rescisão', 'Rescisão'), ('Comissão', 'Comissão'), ('Férias', 'Férias'), ('13° Salário', '13° Salário')], max_length=15, verbose_name='Tipo de Pagamento')),
                ('forma_pagamento', models.CharField(choices=[('Conta Salário', 'Conta Salário'), ('Dinheiro', 'Dinheiro'), ('Transferência', 'Transferência'), ('Pix', 'Pix'), ('Cheque', 'Cheque'), ('Multa Recisória', 'Multa Recisória')], max_length=15, verbose_name='Forma de Pagamento')),
                ('dt_atualizado', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nome_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.cadastro', verbose_name='Funcionário')),
            ],
        ),
        migrations.CreateModel(
            name='Rescisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_desligamento', models.DateField(verbose_name='Dt Desligamento')),
                ('devolucao_uniforme', models.CharField(blank=True, max_length=10, null=True, verbose_name='Devolução Uniforme')),
                ('data_exame_demissional', models.DateField(blank=True, null=True, verbose_name='Dt Demissional')),
                ('data_homologacao', models.DateField(blank=True, null=True, verbose_name='Dt Homologação')),
                ('tipo_desligamento', models.CharField(max_length=30, verbose_name='Forma Desligammento')),
                ('contabilidade_rescisao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contabilidade Rescisão')),
                ('observacao_demissional', models.CharField(blank=True, max_length=20, null=True, verbose_name='Obs Demissional')),
                ('status_rescisao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Status Rescisão')),
                ('dt_atualizado', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nome_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.cadastro', verbose_name='Funcionário')),
            ],
        ),
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('setor', models.CharField(choices=[('Administração', 'Administração'), ('Cozinha', 'Cozinha'), ('Limpeza', 'Limpeza'), ('Sushi', 'Sushi'), ('Salão', 'Salão'), ('Bar', 'Bar'), ('Vallet', 'Vallet')], max_length=13, verbose_name='Setor')),
                ('cargo', models.CharField(choices=[('Gerente Financeiro', 'Gerente Financeiro'), ('Auxiliar Adm', 'Auxiliar Adm'), ('Chef', 'Chef'), ('Cozinheiro', 'Cozinheiro'), ('Cozinheiro Auxiliar', 'Cozinheiro Auxiliar'), ('Faxineira(o)', 'Faxineira(o)'), ('Peixeiro', 'Peixeiro'), ('Sushiman', 'Sushiman'), ('Sushiman Auxiliar', 'Sushiman Auxiliar'), ('Caixa', 'Caixa'), ('Cumin', 'Cumin'), ('Garçom', 'Garçom'), ('Gerente Geral', 'Gerente Geral'), ('Maitre', 'Maitre'), ('Recepcionista', 'Recepcionista'), ('Barman', 'Barman'), ('Copeiro', 'Copeiro'), ('Manobrista', 'Manobrista')], max_length=19, verbose_name='Cargo')),
                ('data_exame_admissional', models.DateField(blank=True, null=True, verbose_name='Dt Exame Admissional')),
                ('data_contratacao', models.DateField(verbose_name='Data Contratação')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Salário')),
                ('documentacao_admissional', models.CharField(blank=True, max_length=10, null=True, verbose_name='Doc Admissional')),
                ('contabilidade_admissional', models.CharField(blank=True, max_length=10, null=True, verbose_name='Doc Contabilidade')),
                ('status_admissional', models.CharField(blank=True, max_length=10, null=True, verbose_name='Status Admissão')),
                ('observacao_admissional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Obs Admissional')),
                ('dt_atualizado', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nome_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.cadastro', verbose_name='Funcionário')),
            ],
            options={
                'unique_together': {('nome_funcionario', 'data_contratacao')},
            },
        ),
    ]
