# Generated by Django 5.1.5 on 2025-03-24 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('users', '0002_tenant_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratacao',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescisao',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tenant'),
            preserve_default=False,
        ),
    ]
