# Generated by Django 5.1.4 on 2025-01-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescisao',
            name='contabilidade_rescisao',
            field=models.CharField(blank=True, choices=[('TRUE', 'Enviado'), ('FALSE', 'Não Enviado')], max_length=10, null=True, verbose_name='Contabilidade Documentação'),
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='data_desligamento',
            field=models.DateField(verbose_name='Data Desligamento'),
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='data_exame_demissional',
            field=models.DateField(blank=True, null=True, verbose_name='Data Exame Demissional'),
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='data_homologacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Homologação'),
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='devolucao_uniforme',
            field=models.CharField(blank=True, choices=[('TRUE', 'Entregue'), ('FALSE', 'Não Entregue')], max_length=10, null=True, verbose_name='Devolução Uniforme'),
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='observacao_demissional',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='status_rescisao',
            field=models.BooleanField(default=False, verbose_name='Status Rescisão'),
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='tipo_desligamento',
            field=models.CharField(choices=[('Dispensa sem justa causa', 'Dispensa sem justa causa'), ('Demissão por justa causa', 'Demissão por justa causa'), ('Pedido de demissão', 'Pedido de demissão'), ('Término do contrato', 'Término do contrato'), ('Rescisão indireta', 'Rescisão indireta'), ('Rescisão por culpa recíproca', 'Rescisão por culpa recíproca')], max_length=30, verbose_name='Forma Desligamento'),
        ),
        migrations.AlterUniqueTogether(
            name='rescisao',
            unique_together={('nome_funcionario', 'data_desligamento')},
        ),
    ]
