# Generated by Django 5.1.4 on 2025-01-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contratacao',
            name='author',
        ),
        migrations.RemoveField(
            model_name='rescisao',
            name='author',
        ),
    ]
