# Generated by Django 5.1.4 on 2025-01-05 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('periodo', models.CharField(choices=[('Almoço', 'Almoço'), ('Jantar', 'Jantar')], max_length=6, verbose_name='Período')),
                ('rodizio', models.IntegerField(verbose_name='Qtd Rodízio')),
                ('dinheiro', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dinheiro')),
                ('pix', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Pix')),
                ('debito_mastercard', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Debito MasterCard')),
                ('debito_visa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Debito Visa')),
                ('debito_elo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Debito Elo')),
                ('credito_mastercard', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Credito MasterCard')),
                ('credito_visa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Credito Visa')),
                ('credito_elo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Credito Elo')),
                ('alelo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alelo')),
                ('american_express', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amex')),
                ('hiper', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='HiperCard')),
                ('sodexo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sodexo')),
                ('ticket_rest', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ticket Refeição')),
                ('vale_refeicao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Vale Refeição')),
                ('dinersclub', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='DinersClub')),
                ('socio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sócio')),
                ('dt_atualizado', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
