# Generated by Django 5.1.5 on 2025-06-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_taxasvendas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxasVendas',
        ),
    ]
