# Generated by Django 5.1.5 on 2025-06-14 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxasVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizado', models.DateTimeField(auto_now=True)),
                ('data_taxa_venda', models.DateField(verbose_name='Data')),
                ('debito_mastercard', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Débito MasterCard')),
                ('debito_visa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Débito Visa')),
                ('debito_elo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Débito Elo')),
                ('credito_mastercard', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Crédito MasterCard')),
                ('credito_visa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Crédito Visa')),
                ('credito_elo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Crédito Elo')),
                ('hiper', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Hiper')),
                ('dinersclub', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Dinersclub')),
                ('american_express', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='American Express')),
                ('alelo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Alelo')),
                ('sodexo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Sodexo')),
                ('vale_refeicao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Vale Refeição')),
                ('ticket_rest', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ticket Rest')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
        ),
    ]
