# Generated by Django 5.1.4 on 2025-01-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Vazio', max_length=165),
            preserve_default=False,
        ),
    ]
