# Generated by Django 5.1.5 on 2025-03-24 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_slug_category_description_and_more'),
        ('users', '0002_tenant_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='carousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tenant'),
            preserve_default=False,
        ),
    ]
