# Generated by Django 5.1.4 on 2024-12-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome_empresa', models.CharField(max_length=50, unique=True, verbose_name='Fornecedor')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('nome_contato', models.CharField(blank=True, max_length=35, null=True, verbose_name='Contato')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade')),
                ('dt_atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_compra', models.DateField(verbose_name='Data da Venda')),
                ('data_vencimento', models.DateField(verbose_name='Data do Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor da Compra')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor de Pagamento')),
                ('qtd', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantidade')),
                ('numero_boleto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Boleto')),
                ('grupo_produto', models.CharField(max_length=20, null=True, verbose_name='Grupo do Produto')),
                ('produto', models.CharField(max_length=20, null=True, verbose_name='Produto')),
                ('classificacao', models.CharField(choices=[('CMV', 'CMV'), ('Gasto Fixo', 'Gasto Fixo'), ('Gasto Variável', 'Gasto Variável')], max_length=20, null=True, verbose_name='Classificação')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão Débito', 'Cartão Débito'), ('Pix', 'Pix'), ('Cheque', 'Cheque'), ('Transferência', 'Transferência'), ('Boleto', 'Boleto'), ('Débito Automático', 'Débito Automático')], max_length=17, null=True, verbose_name='Forma de Pagamento')),
                ('observacao', models.CharField(blank=True, max_length=35, null=True, verbose_name='Observação')),
                ('dt_atualizado', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.fornecedor', verbose_name='Fornecedor')),
            ],
        ),
    ]
