# Generated by Django 5.1.5 on 2025-05-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compras_tenant_fornecedor_tenant'),
        ('users', '0005_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_empresa',
            field=models.CharField(max_length=50, verbose_name='Fornecedor'),
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('tenant', 'nome_empresa')},
        ),
    ]
