# Generated by Django 5.1.5 on 2025-06-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão Débito', 'Cartão Débito'), ('Pix', 'Pix'), ('Cheque', 'Cheque'), ('Transferência', 'Transferência'), ('Boleto', 'Boleto'), ('Débito em Conta', 'Débito em Conta')], max_length=17, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
